apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uod1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0016-tenant/ci1t-830-0016-app/devfile-sample-uod1@sha256:2aea0bfb1982f7f156b96559b269b0b9c215fb8143e55b2d5a70f2b98d29e901
        name: my-nodejs
        resources: {}
status: {}
